@startuml
' define participants
actor User

' Robot_RPC -> MQTT

loop read_commond
        User -> MQTT : Input Mode Selection (1-6)
        ' activate Operator
        ' Operator -> MQTT: Publish mode selection to broker

        ' activate MQTT

        MQTT -> Robot_RPC: Subscribe published mode selection
        activate Robot_RPC

        alt Mode selection = 1
                Robot_RPC -> Robot : automatic
                Robot_RPC -> MQTT : Publish robot state log info to broker
                Robot_RPC -> MQTT : Publish Rosnode log info to broker

        else Mode selection = 2
                Robot_RPC -> Robot : manual
                Robot_RPC -> MQTT : Publish robot state log info to broker
                Robot_RPC -> MQTT : Publish Rosnode log info to broker

        else Mode selection = 3
                Robot_RPC -> Robot : exit
                destroy Robot_RPC

        else Mode selection = 6
                Robot_RPC -> Cloud : 6-download library

                activate Cloud
                Cloud -> Robot : wget dynamic library
                alt Mode selection = 5
                        Robot_RPC -> Robot : Precheck updated library
                        Robot --> MQTT : log Info : Publish Dynamic-lib precheck log info to broker
                        opt Precheck Success
                                alt Mode selection = 4
                                        Robot_RPC -> Robot : reload updated library
                                end
                                deactivate Cloud
                        end

                        opt Precheck Fail
                                Robot -> Robot_RPC :
                        end
                end
        end
        MQTT -> User: Sucribe log info from mqtt broker

end

deactivate MQTT
deactivate Robot_RPC
@enduml
